# - Main configuration -------------------------------------------------------------------------------------------------

base_url = "https://drewfustin.com"
title = "df := 'Drew Fustin'"
description = """
Hello!<br><br> \

I'm Drew Fustin. I live in the peaceful Forest Glen neighborhood of Chicago with my wife, three kids, and dog. \
I'm somewhat of a data leader, having over a decade of experience building data organizations and developing machine \
learning products, at companies ranging from pre-Series A startups to post-IPO megaliths. I've created and managed \
data teams, and I've built and maintained software from end-to-end: infrastructure + feature engineering + model \
training + service deployment. You can find out more about me or schedule some of my time using those links above in \
the header.<br><br>

Under the LLC-pseudonym of <a href="https://www.linkedin.com/company/27018422" target="_blank">Sage Array</a>, I \
provide consulting and contracting services for early- to mid-stage tech companies across the breadth of the data \
science and data engineering disciplines.<br><br>

In another life, I received my PhD in physics from the University of Chicago for \
<a href="https://arxiv.org/abs/2401.07384" target="_blank">studying dark matter by looking for tiny bubbles in a glass \
jar filled with fire suppressent over a mile underground in an active Canadian nickel mine</a>. As you do.
"""
author = "Drew Fustin"
default_language = "en"
output_dir = "public"
build_search_index = true
compile_sass = true
hard_link_static = false
minify_html = false
preserve_dotfiles_in_output = false
generate_feed = true
feed_filename = "atom.xml"
ignored_content = []
ignored_static = []

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = []


# - Markdown configuration ---------------------------------------------------------------------------------------------
[markdown]

highlight_code = true
highlight_theme = "1337"
render_emoji = true
external_links_target_blank = false
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = false
lazy_async_image = false
extra_syntaxes_and_themes = []


# - Link Checker configuration -----------------------------------------------------------------------------------------
[link_checker]

internal_level = "error"
external_level = "error"
skip_prefixes = []
skip_anchor_prefixes = []


# - Slugification strategy ---------------------------------------------------------------------------------------------
[slugify]

paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false


# - Search configuration -----------------------------------------------------------------------------------------------
[search]

include_title = true
include_description = false
include_path = false
include_content = true
index_format = "elasticlunr_javascript"


# - User-Defined Extra configurations ----------------------------------------------------------------------------------
[extra]

# You can put any kind of data here. The data will be accessible in all templates (e.g. {{ config.extra.author }})
# Example:
#     [extra]
#     author = "Famous author"

blog = "/ls"
twitter = "drewfustin"
github = "drewfustin"
linkedin = "drewfustin"
calendly = "drewfustin"
avatar_file = "df-with-glass.jpg"
resume_file = "drewfustin_resume__20240528.pdf"